version: "3.9"
services:
  kannel1:
    image: bulktrade/kannel:r5159
    ports:
      - 13013 # smsbox
      - 13000 # kannel admin
      - 13001 # kannel admin
      - 13014 # kannel admin
      - 13015 # kannel admin
      - 3776
      - 2346
    volumes:
    - "./configs/kannel.conf:/etc/kannel/kannel.conf"
    - "./configs/opensmppbox.conf:/etc/kannel/opensmppbox.conf"
    - "./configs/smpplogins.txt:/etc/kannel/smpplogins.txt"
    - "./configs/sqlbox.conf:/etc/kannel/sqlbox.conf"
  kannel2:
    image: bulktrade/kannel:r5159
    ports:
      - 13013 # smsbox
      - 13000 # kannel admin
      - 13001 # kannel admin
      - 13014 # kannel admin
      - 13015 # kannel admin
      - 3776
      - 2346
    volumes:
    - "./configs/kannel.conf:/etc/kannel/kannel.conf"
    - "./configs/opensmppbox.conf:/etc/kannel/opensmppbox.conf"
    - "./configs/smpplogins.txt:/etc/kannel/smpplogins.txt"
    - "./configs/sqlbox.conf:/etc/kannel/sqlbox.conf"
  kannel3:
    image: bulktrade/kannel:r5159
    ports:
      - 13013 # smsbox
      - 13000 # kannel admin
      - 13001 # kannel admin
      - 13014 # kannel admin
      - 13015 # kannel admin
      - 3776
      - 2346
    volumes:
    - "./configs/kannel.conf:/etc/kannel/kannel.conf"
    - "./configs/opensmppbox.conf:/etc/kannel/opensmppbox.conf"
    - "./configs/smpplogins.txt:/etc/kannel/smpplogins.txt"
    - "./configs/sqlbox.conf:/etc/kannel/sqlbox.conf"
  redis:
    image: redis:alpine
    restart: unless-stopped

  rabbit-mq:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - 8080:15672

  # jasmin:
  #   image: jookies/jasmin:0.10
  #   restart: unless-stopped
  #   container_name: jasmin
  #   volumes:
  #     - /var/log/jasmin:/var/log/jasmin
  #   ports:
  #     - 2775:2775
  #     - 8990:8990
  #     - 1401:1401
  #   depends_on:
  #     - redis
  #     - rabbit-mq
  #   environment:
  #     REDIS_CLIENT_HOST: redis
  #     AMQP_BROKER_HOST: rabbit-mq
  
  jasmin9:
    build: ./jasmin/docker
    restart: unless-stopped
    container_name: jasmin9
    volumes:
      - /var/log/jasmin:/var/log/jasmin
    ports:
      - 2775:2775
      - 8990:8990
      - 1401:1401
    depends_on:
      - redis
      - rabbit-mq
    environment:
      REDIS_CLIENT_HOST: redis
      AMQP_BROKER_HOST: rabbit-mq